ext {
    extName = 'Streamberry'
    extClass = '.Streamberry'
    extVersionCode = 3
    baseUrl = 'https://streamberry.com.br'
    isNsfw = false
}

apply plugin: "kei.plugins.extension.legacy"

android {
    defaultConfig {
        manifestPlaceholders += [SOURCESCHEME: 'https', SOURCEHOST: 'streamberry.com.br']
    }
}

dependencies {
    implementation(project(":lib-multisrc:dooplay"))
    implementation(project(":lib:playlistutils"))
}
