ext {
    extName = 'Streamberry'
    extClass = '.Streamberry'
    extVersionCode = 4
    baseUrl = 'https://streamberry.com.br'
    isNsfw = false
}

apply plugin: "kei.plugins.extension.legacy"

android {
    defaultConfig {
        manifestPlaceholders += [SOURCESCHEME: 'https', SOURCEHOST: 'streamberry.com.br']
    }
}

dependencies {
    implementation(project(":lib:playlistutils"))
    testImplementation(libs.junit)
    testImplementation(libs.bundles.common)
}

android.sourceSets.test.java.srcDirs = ["test"]
android.sourceSets.test.kotlin.srcDirs = ["test"]
