ext {
    extName = 'AnimeQ'
    extClass = '.AnimeQ'
    themePkg = 'dooplay'
    baseUrl = 'https://animeq.cloud'
    overrideVersionCode = 9
    isNsfw = true
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation(project(":lib:bloggerextractor"))
    implementation(project(":lib:playlistutils"))
    testImplementation(libs.junit)
    testImplementation(libs.bundles.common)
}

android.sourceSets.test.java.srcDirs = ["test"]
android.sourceSets.test.kotlin.srcDirs = ["test"]
