ext {
    extName = 'Anime Fire'
    extClass = '.AnimeFire'
    libVersion = 16
    extVersionCode = 14
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation("org.nanohttpd:nanohttpd:2.3.1")
    testImplementation(libs.junit)
    testImplementation(libs.jsoup)
    testImplementation(libs.kotlin.json)
    testImplementation("org.jetbrains.kotlin:kotlin-stdlib:2.3.21")
}

android.sourceSets.test.java.srcDirs = ["test"]

android.sourceSets.test.kotlin.srcDirs = ["test"]

android {
    ndkVersion "27.2.12479018"
    defaultConfig {
        externalNativeBuild {
            cmake {
                abiFilters "arm64-v8a", "armeabi-v7a"
            }
        }
    }
    externalNativeBuild {
        cmake {
            path file("src/main/cpp/CMakeLists.txt")
            version "3.22.1"
        }
    }
    buildTypes {
        release {
            proguardFiles("proguard-rules.pro")
        }
    }
    packaging {
        jniLibs {
            useLegacyPackaging true
        }
    }
}
