ext {
    extName = 'YUMEFREE'
    extClass = '.YumeFree'
    extVersionCode = 2
}

apply plugin: "kei.plugins.extension.legacy"

dependencies {
    implementation(project(":lib:bloggerextractor"))
    implementation(project(":lib:vidmolyextractor"))
    implementation(project(":lib:playlistutils"))
}
